// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"time"
)

type Comment struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Contents  string
	Userid    int32
	Postid    int32
}

type Commentlike struct {
	ID        int32
	CreatedAt time.Time
	Userid    int32
	Commentid int32
}

type Follower struct {
	ID         int32
	CreatedAt  time.Time
	Leaderid   int32
	Followerid int32
}

type Hashtag struct {
	ID        int32
	CreatedAt time.Time
	Title     string
}

type Post struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
	Caption   string
	Userid    int32
}

type Postlike struct {
	ID        int32
	CreatedAt time.Time
	Userid    int32
	Postid    int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Bio       string
	Avatar    string
	Email     string
	Password  string
}
