// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package pg

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (contents, userId, postId)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, contents, userid, postid
`

type CreateCommentParams struct {
	Contents string
	Userid   int32
	Postid   int32
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Contents, arg.Userid, arg.Postid)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Contents,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const createCommentLike = `-- name: CreateCommentLike :one
INSERT INTO commentLikes (userId, commentId)
VALUES ($1, $2)
RETURNING id, created_at, userid, commentid
`

type CreateCommentLikeParams struct {
	Userid    int32
	Commentid int32
}

func (q *Queries) CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) (Commentlike, error) {
	row := q.db.QueryRowContext(ctx, createCommentLike, arg.Userid, arg.Commentid)
	var i Commentlike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Userid,
		&i.Commentid,
	)
	return i, err
}

const createFollower = `-- name: CreateFollower :one
INSERT INTO followers (leaderId, followerId)
VALUES ($1, $2)
RETURNING id, created_at, leaderid, followerid
`

type CreateFollowerParams struct {
	Leaderid   int32
	Followerid int32
}

func (q *Queries) CreateFollower(ctx context.Context, arg CreateFollowerParams) (Follower, error) {
	row := q.db.QueryRowContext(ctx, createFollower, arg.Leaderid, arg.Followerid)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Leaderid,
		&i.Followerid,
	)
	return i, err
}

const createHashtag = `-- name: CreateHashtag :one
INSERT INTO hashtags (title)
VALUES ($1)
RETURNING id, created_at, title
`

func (q *Queries) CreateHashtag(ctx context.Context, title string) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, createHashtag, title)
	var i Hashtag
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Title)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (url, caption, userId)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, url, caption, userid
`

type CreatePostParams struct {
	Url     string
	Caption string
	Userid  int32
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Url, arg.Caption, arg.Userid)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Caption,
		&i.Userid,
	)
	return i, err
}

const createPostLike = `-- name: CreatePostLike :one
INSERT INTO postLikes (userId, postId)
VALUES ($1, $2)
RETURNING id, created_at, userid, postid
`

type CreatePostLikeParams struct {
	Userid int32
	Postid int32
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (Postlike, error) {
	row := q.db.QueryRowContext(ctx, createPostLike, arg.Userid, arg.Postid)
	var i Postlike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, bio, avatar, email, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, username, bio, avatar, email, password
`

type CreateUserParams struct {
	Username string
	Bio      string
	Avatar   string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Bio,
		arg.Avatar,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Bio,
		&i.Avatar,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments
WHERE id = $1
RETURNING id, created_at, updated_at, contents, userid, postid
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) (Comment, error) {
	row := q.db.QueryRowContext(ctx, deleteComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Contents,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const deleteCommentLike = `-- name: DeleteCommentLike :one
DELETE FROM commentLikes
WHERE id = $1
RETURNING id, created_at, userid, commentid
`

func (q *Queries) DeleteCommentLike(ctx context.Context, id int32) (Commentlike, error) {
	row := q.db.QueryRowContext(ctx, deleteCommentLike, id)
	var i Commentlike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Userid,
		&i.Commentid,
	)
	return i, err
}

const deleteFollower = `-- name: DeleteFollower :one
DELETE FROM followers
WHERE id = $1
RETURNING id, created_at, leaderid, followerid
`

func (q *Queries) DeleteFollower(ctx context.Context, id int32) (Follower, error) {
	row := q.db.QueryRowContext(ctx, deleteFollower, id)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Leaderid,
		&i.Followerid,
	)
	return i, err
}

const deleteHashtag = `-- name: DeleteHashtag :one
DELETE FROM hashtags
WHERE id = $1
RETURNING id, created_at, title
`

func (q *Queries) DeleteHashtag(ctx context.Context, id int32) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, deleteHashtag, id)
	var i Hashtag
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Title)
	return i, err
}

const deletePost = `-- name: DeletePost :one
DELETE FROM posts
WHERE id = $1
RETURNING id, created_at, updated_at, url, caption, userid
`

func (q *Queries) DeletePost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRowContext(ctx, deletePost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Caption,
		&i.Userid,
	)
	return i, err
}

const deletePostLike = `-- name: DeletePostLike :one
DELETE FROM postLikes
WHERE id = $1
RETURNING id, created_at, userid, postid
`

func (q *Queries) DeletePostLike(ctx context.Context, id int32) (Postlike, error) {
	row := q.db.QueryRowContext(ctx, deletePostLike, id)
	var i Postlike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, created_at, updated_at, username, bio, avatar, email, password
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Bio,
		&i.Avatar,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, created_at, updated_at, contents, userid, postid FROM comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int32) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Contents,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const getCommentLike = `-- name: GetCommentLike :one
SELECT id, created_at, userid, commentid FROM commentLikes
WHERE id = $1
`

func (q *Queries) GetCommentLike(ctx context.Context, id int32) (Commentlike, error) {
	row := q.db.QueryRowContext(ctx, getCommentLike, id)
	var i Commentlike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Userid,
		&i.Commentid,
	)
	return i, err
}

const getFollower = `-- name: GetFollower :one
SELECT id, created_at, leaderid, followerid FROM followers
WHERE id = $1
`

func (q *Queries) GetFollower(ctx context.Context, id int32) (Follower, error) {
	row := q.db.QueryRowContext(ctx, getFollower, id)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Leaderid,
		&i.Followerid,
	)
	return i, err
}

const getHashtag = `-- name: GetHashtag :one
SELECT id, created_at, title FROM hashtags
WHERE title = $1
`

func (q *Queries) GetHashtag(ctx context.Context, title string) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, getHashtag, title)
	var i Hashtag
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Title)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, created_at, updated_at, url, caption, userid FROM posts
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Caption,
		&i.Userid,
	)
	return i, err
}

const getPostLike = `-- name: GetPostLike :one
SELECT id, created_at, userid, postid FROM postLikes
WHERE id = $1
`

func (q *Queries) GetPostLike(ctx context.Context, id int32) (Postlike, error) {
	row := q.db.QueryRowContext(ctx, getPostLike, id)
	var i Postlike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, username, bio, avatar, email, password FROM users
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Bio,
		&i.Avatar,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserID = `-- name: GetUserID :one
SELECT id, created_at, updated_at, username, bio, avatar, email, password FROM users
WHERE id = $1
`

func (q *Queries) GetUserID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Bio,
		&i.Avatar,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const likesComment = `-- name: LikesComment :many
SELECT id, created_at, userid, commentid FROM commentLikes
WHERE commentId = $1
`

func (q *Queries) LikesComment(ctx context.Context, commentid int32) ([]Commentlike, error) {
	rows, err := q.db.QueryContext(ctx, likesComment, commentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commentlike
	for rows.Next() {
		var i Commentlike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Userid,
			&i.Commentid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likesPost = `-- name: LikesPost :many
SELECT id, created_at, userid, postid FROM postLikes
WHERE postId= $1
`

func (q *Queries) LikesPost(ctx context.Context, postid int32) ([]Postlike, error) {
	rows, err := q.db.QueryContext(ctx, likesPost, postid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postlike
	for rows.Next() {
		var i Postlike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Userid,
			&i.Postid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentLikes = `-- name: ListCommentLikes :many
SELECT id, created_at, userid, commentid FROM commentLikes
ORDER BY id
`

func (q *Queries) ListCommentLikes(ctx context.Context) ([]Commentlike, error) {
	rows, err := q.db.QueryContext(ctx, listCommentLikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commentlike
	for rows.Next() {
		var i Commentlike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Userid,
			&i.Commentid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT id, created_at, updated_at, contents, userid, postid FROM comments
ORDER BY id
`

func (q *Queries) ListComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Contents,
			&i.Userid,
			&i.Postid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsPost = `-- name: ListCommentsPost :many
SELECT id, created_at, updated_at, contents, userid, postid FROM comments
WHERE postId= $1
`

func (q *Queries) ListCommentsPost(ctx context.Context, postid int32) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsPost, postid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Contents,
			&i.Userid,
			&i.Postid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT id, created_at, leaderid, followerid FROM followers
ORDER BY id
`

func (q *Queries) ListFollowers(ctx context.Context) ([]Follower, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Follower
	for rows.Next() {
		var i Follower
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Leaderid,
			&i.Followerid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHashtags = `-- name: ListHashtags :many
SELECT id, created_at, title FROM hashtags
ORDER BY id
`

func (q *Queries) ListHashtags(ctx context.Context) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, listHashtags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hashtag
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostLikes = `-- name: ListPostLikes :many
SELECT id, created_at, userid, postid FROM postLikes
ORDER BY id
`

func (q *Queries) ListPostLikes(ctx context.Context) ([]Postlike, error) {
	rows, err := q.db.QueryContext(ctx, listPostLikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postlike
	for rows.Next() {
		var i Postlike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Userid,
			&i.Postid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, created_at, updated_at, url, caption, userid FROM posts
ORDER BY id
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.Caption,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsUser = `-- name: ListPostsUser :many
SELECT id, created_at, updated_at, url, caption, userid FROM posts
WHERE userId= $1
`

func (q *Queries) ListPostsUser(ctx context.Context, userid int32) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.Caption,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, updated_at, username, bio, avatar, email, password FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Bio,
			&i.Avatar,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET contents = $2
WHERE id = $1
RETURNING id, created_at, updated_at, contents, userid, postid
`

type UpdateCommentParams struct {
	ID       int32
	Contents string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Contents)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Contents,
		&i.Userid,
		&i.Postid,
	)
	return i, err
}

const updateHashtag = `-- name: UpdateHashtag :one
UPDATE hashtags
SET title = $2
WHERE id = $1
RETURNING id, created_at, title
`

type UpdateHashtagParams struct {
	ID    int32
	Title string
}

func (q *Queries) UpdateHashtag(ctx context.Context, arg UpdateHashtagParams) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, updateHashtag, arg.ID, arg.Title)
	var i Hashtag
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Title)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET url = $2, caption = $3
WHERE id = $1
RETURNING id, created_at, updated_at, url, caption, userid
`

type UpdatePostParams struct {
	ID      int32
	Url     string
	Caption string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost, arg.ID, arg.Url, arg.Caption)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Caption,
		&i.Userid,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET bio = $2, avatar = $3
WHERE id = $1
RETURNING id, created_at, updated_at, username, bio, avatar, email, password
`

type UpdateUserParams struct {
	ID     int32
	Bio    string
	Avatar string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Bio, arg.Avatar)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Bio,
		&i.Avatar,
		&i.Email,
		&i.Password,
	)
	return i, err
}
